# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-306cc8bd-a6db-4468-8358-9d5a22d33766";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-306cc8bd-a6db-4468-8358-9d5a22d33766".device = "/dev/disk/by-uuid/306cc8bd-a6db-4468-8358-9d5a22d33766";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AC63-DBDD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/smol" =
    { device = "/dev/disk/by-uuid/b42c3d05-84c0-4375-ae80-af27c855b412";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
